---
title: "Project3-Presentation-Team4"
author: "Jiawen Liu, Jiongqi Zhao, Zhongxuan Liu, Chenze Li"
date: "3/14/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)

covid <- read_csv("https://covid19.who.int/WHO-COVID-19-global-data.csv")
covid$WHO_region<-as.factor(covid$WHO_region)
```


```{r}
#causal inference
library(tidyverse)
library(lubridate)
data3<-read_csv("C:/Users/Tony Li/Desktop/project3/data_c.csv",col_names = T)
data3f<-read_csv("C:/Users/Tony Li/Desktop/project3/data_c1.csv",col_names = T)
colnames(data3f)[1]<-"country_code"
colnames(data3)[1]<-"country_code"
sumn<-function(x){
  return (sum(x,na.rm=T))
}
data3f$days<-apply(data3f[,3:431],1,sumn)
pos<-function(x){
  return (which(x==2))
}
data3_pos<-apply(data3[,3:431],1,pos)
names(data3_pos)<-1:186

data3_pos1<-sapply(data3_pos,length)
data3_pos1<-data3_pos1[which(data3_pos1>=22)]
data3_pos<-data3[as.integer(names(data3_pos1)),]
posq<-function(x){
  return (which(x==2)[1])
}
pos1<-apply(data3_pos[,3:431],1,posq)
date<-colnames(data3_pos)[pos1+2]
Sys.setlocale("LC_TIME", "C")
date<-as.Date(date,"%d-%b-%y")
date<-data.frame(country_code=data3_pos$country_code,date=date)
library(countrycode)
library(ISOcodes)
covid_<-covid
covid_$country_code<-countrycode(covid$Country,origin = "country.name",destination = "iso3c",warn = TRUE)
c<-c(integer(0))
for (i in 1:153){
  c<-c(c,which(covid_$country_code==data3_pos$country_code[i]))
  
}

covid_<-covid_[c,]
newd<-inner_join(covid_, data3_pos, by = "country_code")
newd<-inner_join(newd,date, by = "country_code")
newd<-newd[,c(1:10,440)]

day<-newd[seq(1,64904,by=427),]$date
code<-unique(newd$country_code)

data4<-data.frame(integer(0))
for (i in 1:152){
covid_temp<-filter(newd,country_code==code[i])

covid_temp_un<-filter(covid_temp,as.Date(date[i])-10<=Date_reported,Date_reported<=date[i])
covid_temp_lo<-filter(covid_temp,date[i]<=Date_reported,Date_reported<=as.Date(date[i])+10)

covid_temp_un$rate<-c(NA,covid_temp_un$New_cases[2:11]/covid_temp_un$Cumulative_cases[1:10])
covid_temp_lo$rate<-c(NA,covid_temp_lo$New_cases[2:11]/covid_temp_lo$Cumulative_cases[1:10])
covid_temp_un$status<-rep(0,11)
covid_temp_lo$status<-rep(1,11)

temp1<-as.data.frame(rbind(covid_temp_un[2:11,],covid_temp_lo[2:11,]))
data4<-as.data.frame(rbind(data4,temp1))
}

```

```{r}
pos2<-which(data4$rate==NaN|data4$rate==Inf)
data4<-filter(data4,!(country_code%in%unique(data4$country_code[pos2])))
data4$status<-as.factor(data4$status)
data4$country_code<-as.factor(data4$country_code)

fit3<-aov(rate~status+country_code,data=data4)
summary(fit3)

data4$status = relevel(data4$status,ref='0')
fit4 = glm(status~country_code,family = binomial,data = data4)
prob = fit4$fitted.values
pscore = ifelse(data4$rate=='1',prob,(1-prob))
weight = 1/pscore

model_new1= aov(rate~status+country_code,data = data4,weights = weight)
summary(model_new1)
```
```{r}
fit5<-aov(rate~status+country_code+status:country_code,data=data4)
anova(fit3,fit5)
```
```{r}
plot(fit3, which=c(1,2,3,6))
```
```{r}
#US	
#IN	
#BR
#RU
#GB
#FR
dat<-filter(data4,Country=="China")
acf(dat[1:10,]$rate)
pacf(dat[1:10,]$rate)
resm4<-arima(dat[1:10,]$rate, order=c(2,0,0))
pred4 <- predict(resm4, n.ahead=10, se.fit=TRUE)
plot(x=11:20,dat[11:20,]$rate)
lines(11:20,pred4$pred,col=3,type="b")
datnew<-data.frame(x1=c(dat[11:20,]$rate,pred4$pred),x2=c(rep(1,10),rep(0,10)))
summary(lm(x1~x2,data=datnew))
```

```{r}
plot(x=1:20,dat[1:20,]$rate)
```

```{r}
data41<-data.frame(integer(0))
n=12
for (i in 1:152){
covid_temp<-filter(newd,country_code==code[i])

covid_temp_un<-filter(covid_temp,Date_reported<=date[i])
covid_temp_lo<-filter(covid_temp,date[i]<=Date_reported,Date_reported<=as.Date(date[i])+n)

covid_temp_un$rate<-c(NA,covid_temp_un$New_cases[2:length(covid_temp_un$New_cases)]/covid_temp_un$Cumulative_cases[1:length(covid_temp_un$New_cases)-1])
covid_temp_lo$rate<-c(NA,covid_temp_lo$New_cases[2:(n+1)]/covid_temp_lo$Cumulative_cases[1:n])
covid_temp_un$status<-rep(0,length(covid_temp_un$New_cases))
covid_temp_lo$status<-rep(1,(n+1))

temp1<-as.data.frame(rbind(covid_temp_un[2:length(covid_temp_un$New_cases),],covid_temp_lo[2:(n+1),]))
data41<-as.data.frame(rbind(data41,temp1))
}

#pos21<-which(is.nan(data41$rate)==|data41$rate==Inf)
#data41<-filter(data41,!(country_code%in%unique(data41$country_code[pos21])))

newdata<-filter(data41,(Country_code%in%c("US","UK","IN","AU","ET")))
UK<-filter(data41,(Country_code%in%c("GB")))
IN<-filter(data41,(Country_code%in%c("IN")))
AU<-filter(data41,(Country_code%in%c("AU")))
ET<-filter(data41,(Country_code%in%c("ET")))
US<-filter(data41,(Country_code%in%c("US")))
```

```{r}

data<-UK[30:(length(UK$rate)-n),]$rate
acf(data)
pacf(data)
resm4<-arima(data[30:(length(UK$rate)-n)], order=c(6,0,0))
pred4 <- predict(resm4, n.ahead=n, se.fit=TRUE)
fdat<-data.frame(new_cases=c(pred4$pred,UK[(length(UK$rate)-n+1):length(UK$rate),]$rate),status=c(rep(0,n),rep(1,n)),Country=rep("UK",(2*n)))
Box.test(resm4$residuals,type="Ljung")

datain<-IN[30:(length(IN$rate)-n),]$rate
acf(datain)
pacf(datain)
resm4<-arima(datain[30:(length(IN$rate)-n)], order=c(1,0,0))
pred4 <- predict(resm4, n.ahead=n, se.fit=TRUE)
fdatin<-data.frame(new_cases=c(pred4$pred,IN[(length(IN$rate)-n+1):length(IN$rate),]$rate),status=c(rep(0,n),rep(1,n)),Country=rep("IN",(2*n)))
Box.test(resm4$residuals,type="Ljung")

dataau<-AU[24:(length(AU$rate)-n),]$rate
acf(dataau)
pacf(dataau)
resm4<-arima(dataau[24:(length(AU$rate)-n)], order=c(4,0,0))
pred4 <- predict(resm4, n.ahead=n, se.fit=TRUE)
fdatau<-data.frame(new_cases=c(pred4$pred,AU[(length(AU$rate)-n+1):length(AU$rate),]$rate),status=c(rep(0,n),rep(1,n)),Country=rep("AU",(2*n)))
Box.test(resm4$residuals,type="Ljung")


dataus<-US[18:(length(US$rate)-n),]$rate
acf(dataus)
pacf(dataus)
resm4<-arima(dataus[18:(length(US$rate)-n)], order=c(5,0,0))
pred4 <- predict(resm4, n.ahead=n, se.fit=TRUE)
fdatus<-data.frame(new_cases=c(pred4$pred,US[(length(US$rate)-n+1):length(US$rate),]$rate),status=c(rep(0,n),rep(1,n)),Country=rep("US",(2*n)))



new<-as.data.frame(rbind(fdat,fdatin,fdatau))
new$Country<-as.factor(new$Country)
fit1<-aov(new_cases~Country+status+Country:status,data=new)
fit2<-aov(new_cases~Country+status,data=new)
anova(fit1,fit2)
M<-summary(fit1)
new$status<-as.factor(new$status)

new$status = relevel(new$status,ref='0')
fit4 = glm(status~Country,family = binomial,data = new)
prob = fit4$fitted.values
pscore = ifelse(new$new_cases=='1',prob,(1-prob))
weight = 1/pscore

model_new1= aov(new_cases~status+Country,data = new,weights = weight)
summary(model_new1)

```

```{r}
summary(fit2)
```
```{r}
fdat$Date<-UK$Date_reported[(length(UK$rate)-n+1):length(UK$rate)]
fdat$status<-as.factor(fdat$status)
levels(fdat$status)<-c("Predicted","Real")
library(ggplot2)
ggplot(data = fdat, mapping = aes(x = Date, y = new_cases, linetype = status, colour = status, shape = status,fill=status))+
geom_line() + 
  geom_point()+ #绘制线图和点图
scale_linetype_manual(values = c(1,2))+ #自定义线条类型
scale_color_manual(values = c('blue','red'))+ #自定义颜色
scale_shape_manual(values = c(21,23))+ #自定义点形状
scale_fill_manual(values = c('black','yellow'))+
  labs(y = "Percentage Change",
                  x = "Date",title="United Kingdom")+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
fdatau$Date<-AU$Date_reported[(length(AU$rate)-n+1):length(AU$rate)]
fdatau$status<-as.factor(fdatau$status)
levels(fdatau$status)<-c("Predicted","Real")
library(ggplot2)
ggplot(data = fdatau, mapping = aes(x = Date, y = new_cases, linetype = status, colour = status, shape = status,fill=status))+
geom_line() + 
  geom_point()+ #绘制线图和点图
scale_linetype_manual(values = c(1,2))+ #自定义线条类型
scale_color_manual(values = c('blue','red'))+ #自定义颜色
scale_shape_manual(values = c(21,23))+ #自定义点形状
scale_fill_manual(values = c('black','yellow'))+
  labs(y = "Percentage Change",
                  x = "Date",title="Australia")+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
fdatin$Date<-IN$Date_reported[(length(IN$rate)-n+1):length(IN$rate)]
fdatin$status<-as.factor(fdatin$status)
levels(fdatin$status)<-c("Predicted","Real")
library(ggplot2)
ggplot(data = fdatin, mapping = aes(x = Date, y = new_cases, linetype = status, colour = status, shape = status,fill=status))+
geom_line() + 
  geom_point()+ #绘制线图和点图
scale_linetype_manual(values = c(1,2))+ #自定义线条类型
scale_color_manual(values = c('blue','red'))+ #自定义颜色
scale_shape_manual(values = c(21,23))+ #自定义点形状
scale_fill_manual(values = c('black','yellow'))+
  labs(y = "Percentage Change",
                  x = "Date",title="India")+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
library(kableExtra)
kable(summary(fit))
```

